# Generated by Django 6.1 on 2026-08-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='police_station',
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('THEFT', 'Theft'), ('FRAUD', 'Fraud'), ('ASSAULT', 'Assault'), ('CYBERCRIME', 'Cyber Crime'), ('MISSING', 'Missing Person'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
