# Generated by Django 6.1 on 2026-08-27 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_documentversion_digital_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('SIGNED', 'Digitally Signed')], default='DRAFT', max_length=20),
        ),
    ]
