# Generated by Django 6.1 on 2026-08-27 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_documentversion_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_officers',
            field=models.ManyToManyField(blank=True, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
