# Generated by Django 6.1 on 2026-08-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_assigned_to_alter_case_assigned_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
