# Generated by Django 6.1 on 2026-08-28 09:46

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_documentversion_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to=cases.models.document_version_upload_path),
        ),
    ]
