# Generated by Django 6.1 on 2026-08-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('IO', 'Investigating Officer'), ('SHO', 'Station House Officer'), ('FORENSIC_OFFICER', 'Forensic Officer')], default='IO', max_length=20),
        ),
    ]
