# Generated by Django 6.1 on 2026-08-27 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0005_documentversion_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CASE_CREATED', 'Case Created'), ('DOCUMENT_CREATED', 'Document Created'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VERSION_UPLOADED', 'Document Version Uploaded'), ('DOCUMENT_SUBMITTED', 'Document Submitted for Review'), ('DOCUMENT_APPROVED', 'Document Approved'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('DOCUMENT_SIGNED', 'Document Digitally Signed'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.case')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.document')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.documentversion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
